<a href="https://colab.research.google.com/github/umair986/ML_basics/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


In [3]:
!nvidia-sm

/bin/bash: line 1: nvidia-sm: command not found


In [4]:
##Tensors
scalar = torch.tensor(7)
scalar


tensor(7)

In [5]:
scalar.ndim

0

In [6]:
#get scalar back as int
scalar.item()

7

In [7]:
vector = torch.tensor([7,3])
vector

tensor([7, 3])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

**Random Tensors**

``start with random number ->  look at data -> update random numbers -> look at data -> update random numbers ``

In [25]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4382, 0.4523, 0.1617, 0.9548],
        [0.6081, 0.7723, 0.1874, 0.8865],
        [0.7159, 0.1942, 0.3126, 0.0787]])

In [19]:
random_tensor.ndim


3

In [20]:
random_image_size = torch.rand(size=(224,224,3)) #where height,widht,color channel(R,G,B)
random_image_size.shape,random_image_size.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
#create tensor for all zero used for creating mask
eros = torch.zeros(size=(3,4))
eros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
eros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
eros.dtype

torch.float32

In [28]:
random_tensor.dtype

torch.float32