<a href="https://colab.research.google.com/github/umair986/ML_basics/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


In [ ]:
!nvidia-sm

/bin/bash: line 1: nvidia-sm: command not found


In [ ]:
##Tensors
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get scalar back as int
scalar.item()

7

In [ ]:
vector = torch.tensor([7,3])
vector

tensor([7, 3])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

**Random Tensors**

``start with random number ->  look at data -> update random numbers -> look at data -> update random numbers ``

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0723, 0.3262, 0.4034, 0.6157],
        [0.3519, 0.8475, 0.2498, 0.1548],
        [0.5695, 0.5467, 0.4266, 0.7523]])

In [ ]:
random_tensor.ndim


2

In [ ]:
random_image_size = torch.rand(size=(224,224,3)) #where height,widht,color channel(R,G,B)
random_image_size.shape,random_image_size.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
#create tensor for all zero used for creating mask
eros = torch.zeros(size=(3,4))
eros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
eros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
eros.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

Create a range of tensor or tensor like


In [ ]:
one_to_ten = torch.arange(start=1, end=11 , step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
torch.__version__

'2.5.1+cu124'

In [ ]:
#creating tensor like
ten_zeros = torch.zeros_like(input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Tensors datatypes
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device ='cpu',# defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
int_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

**Getting information from tensors**

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

shape - what shape is the tensor? (some operations require specific shape rules)
dtype - what datatype are the elements within the tensor stored in?
device - what device is the tensor stored on? (usually GPU or CPU)

In [ ]:
#Getting infos from tensors
some_tensor = torch.rand(3,4)
some_tensor = some_tensor.type(torch.float32)
some_tensor

tensor([[0.5033, 0.1498, 0.6422, 0.1145],
        [0.0096, 0.5873, 0.8509, 0.3990],
        [0.9391, 0.4339, 0.6750, 0.7975]])

In [ ]:
#details about tensor
print(some_tensor)
print(f"Datatype:{some_tensor.dtype}")
print(f"Shape:" , some_tensor.shape)
print(f"Device:" , some_tensor.device) #default is CPU

tensor([[0.5033, 0.1498, 0.6422, 0.1145],
        [0.0096, 0.5873, 0.8509, 0.3990],
        [0.9391, 0.4339, 0.6750, 0.7975]])
Datatype:torch.float32
Shape: torch.Size([3, 4])
Device: cpu


**Manipulating tensors **

(tensor operations)
In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between


Addition


Substraction

Multiplication (element-wise)

Division

Matrix multiplication

In [ ]:
tensor = torch.tensor([2,3,4])
tensor + 10

tensor([12, 13, 14])

In [ ]:
tensor * 10


tensor([20, 30, 40])

In [ ]:
tensor / 10

tensor([0.2000, 0.3000, 0.4000])

In [ ]:
#pytorch built in func
torch.mul(tensor,10)

tensor([20, 30, 40])

In [ ]:
torch.add(tensor,10)


tensor([12, 13, 14])

**Matri Multiplication**

Operation	Calculation	Code

Element-wise multiplication	[1*1, 2*2, 3*3] = [1, 4, 9]	tensor * tensor

Matrix multiplication	[1*1 + 2*2 + 3*3] = [14]	tensor.matmul(tensor)

**The inner dimensions must match:**

(3, 2) @ (3, 2) won't work

(2, 3) @ (3, 2) will work

(3, 2) @ (2, 3) will work


**The resulting matrix has the shape of the outer dimensions:**

(2, 3) @ (3, 2) -> (2, 2)

(3, 2) @ (2, 3) -> (3, 3)


In [ ]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.2712, 0.2207, 0.3646],
        [0.2813, 0.2240, 0.3694],
        [0.3439, 0.2779, 0.4588]])

In [ ]:
print (tensor , "*", tensor)
print ("Equals:", tensor*tensor)

tensor([2, 3, 4]) * tensor([2, 3, 4])
Equals: tensor([ 4,  9, 16])


In [ ]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(29)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
  print(value)

tensor(4)
tensor(13)
tensor(29)
CPU times: user 1.78 ms, sys: 0 ns, total: 1.78 ms
Wall time: 1.87 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 95 µs, sys: 19 µs, total: 114 µs
Wall time: 83.7 µs


tensor(29)

In [ ]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(29)

One of the most common errors in deep learning (shape errors)
Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.



In [ ]:
#Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])

tensor_B = torch.tensor([[7,10],[8,11],[9,12]])

torch.matmul(tensor_A , tensor_B)
#Intentional Error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.


One of the ways to do this is with a transpose (switch the dimensions of a given tensor).


You can perform transposes in PyTorch using either:


torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
tensor.T - where tensor is the desired tensor to transpose.

In [ ]:
tensor_B.T,tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# The operation works when tensor_B is transposed
print(f"orginal shapes of tensor A : {tensor_A.shape} and tensor B : {tensor_B.shape}")
print(f"New shapes of tensor A : {tensor_A.shape} and tensor B transpose : {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

orginal shapes of tensor A : torch.Size([3, 2]) and tensor B : torch.Size([3, 2])
New shapes of tensor A : torch.Size([3, 2]) and tensor B transpose : torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [ ]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
#create a range
x =  torch.arange(0,100,10) #from o to  hundred with a gap or difference of 10
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#find minimum
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [ ]:
#find max
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [ ]:
#find mean note torch.mean func works on int and float 32s
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#find sum
torch.sum(x) , x.sum()


(tensor(450), tensor(450))

**Positional min/max**

You can also find the index of a tensor where the max or minimum occurs with torch.argmax() and torch.argmin() respectively.


This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the softmax activation function).

In [ ]:
min_val = torch.argmin(x)
print("Index position of min value is : " , min_val)

Index position of min value is :  tensor(0)


In [ ]:
max_val = torch.argmax(x)
print("Index position of max value is : " , max_val)

Index position of max value is :  tensor(9)


In [ ]:
W = torch.tensor([-1,2])
X = torch.tensor([3,-2])
y = torch.sigmoid(1 + X.T @ W)
print(y)

tensor(0.0025)


<ipython-input-62-8009dd36979b>:3: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3683.)
  y = torch.sigmoid(1 + X.T @ W)


In [ ]:
torch.manual_seed(0)

class MyDenseLayer(torch.nn.Module):
  def __init__(self, input_dim , out_dim):
    super(MyDenseLayer, self).__init__()
    self.weight = torch.nn.Parameter(torch.randn(input_dim, out_dim))
    self.bias = torch.nn.Parameter(torch.randn(out_dim))

  def forward(self, x):
      z = x @ self.weight + self.bias
      output = torch.sigmoid(z)
      return output

X = torch.tensor([-1, 2], dtype=torch.float)
model = MyDenseLayer(2, 2)
y = model(X)
print(y)


tensor([0.0009, 0.5079], grad_fn=<SigmoidBackward0>)


Finding the min, max, mean, sum, etc (aggregation)
Now we've seen a few ways to manipulate tensors, let's run through a few ways to aggregate them (go from more values to less values).

First we'll create a tensor and then find the max, min, mean and sum of it.

In [ ]:
c = torch.arange(0,100,10)
c

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f"Min : {c.min()}")
print(f"Ma : {c.max()}")
print(f"Mean : {c.type(torch.float32).mean()}")

Min : 0
Ma : 90
Mean : 45.0


In [ ]:
import torch
x = torch.arange(1.,8.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_reshaped = x.reshape(1,7)
x_reshaped , x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Change view data remains the same


In [ ]:
z = x.view(1,7)
z ,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.

So changing the view changes the original tensor too.

In [ ]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))