<a href="https://colab.research.google.com/github/umair986/ML_basics/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


In [ ]:
!nvidia-sm

/bin/bash: line 1: nvidia-sm: command not found


In [ ]:
##Tensors
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get scalar back as int
scalar.item()

7

In [ ]:
vector = torch.tensor([7,3])
vector

tensor([7, 3])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

**Random Tensors**

``start with random number ->  look at data -> update random numbers -> look at data -> update random numbers ``

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9496, 0.3522, 0.6388, 0.1392],
        [0.4107, 0.3830, 0.5363, 0.7583],
        [0.3361, 0.1981, 0.4291, 0.9026]])

In [ ]:
random_tensor.ndim


2

In [ ]:
random_image_size = torch.rand(size=(224,224,3)) #where height,widht,color channel(R,G,B)
random_image_size.shape,random_image_size.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
#create tensor for all zero used for creating mask
eros = torch.zeros(size=(3,4))
eros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
eros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
eros.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

Create a range of tensor or tensor like


In [ ]:
one_to_ten = torch.arange(start=1, end=11 , step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
torch.__version__

'2.5.1+cu121'

In [ ]:
#creating tensor like
ten_zeros = torch.zeros_like(input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Tensors datatypes
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device ='cpu',# defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
int_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

**Getting information from tensors**

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

shape - what shape is the tensor? (some operations require specific shape rules)
dtype - what datatype are the elements within the tensor stored in?
device - what device is the tensor stored on? (usually GPU or CPU)

In [ ]:
#Getting infos from tensors
some_tensor = torch.rand(3,4)
some_tensor = some_tensor.type(torch.float32)
some_tensor

tensor([[0.9955, 0.1951, 0.0292, 0.9495],
        [0.7452, 0.6730, 0.9764, 0.2162],
        [0.6038, 0.4063, 0.0035, 0.6193]])

In [ ]:
#details about tensor
print(some_tensor)
print(f"Datatype:{some_tensor.dtype}")
print(f"Shape:" , some_tensor.shape)
print(f"Device:" , some_tensor.device) #default is CPU

tensor([[0.9955, 0.1951, 0.0292, 0.9495],
        [0.7452, 0.6730, 0.9764, 0.2162],
        [0.6038, 0.4063, 0.0035, 0.6193]])
Datatype:torch.float32
Shape: torch.Size([3, 4])
Device: cpu


**Manipulating tensors **

(tensor operations)
In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between


Addition


Substraction

Multiplication (element-wise)

Division

Matrix multiplication

In [ ]:
tensor = torch.tensor([2,3,4])
tensor + 10

tensor([12, 13, 14])

In [ ]:
tensor = tensor * 10
tensor

tensor([20, 30, 40])

In [ ]:
tensor - 10

tensor([10, 20, 30])